version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - MODEL_TYPE
        - MODEL_PATH
        - FLASK_ENV
        - LOG_LEVEL
    ports:
      - "7000:5000"
    env_file:
      - sample.env
    volumes:
      - .:/app
