version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MODEL_TYPE=nllb-600m
      - MODEL_PATH=/models/nllb-600m
      - LOG_LEVEL=INFO
    volumes:
      - .:/app
